import styles from '../styles/Presentation.module.css'
import HeadBar from '../components/HeadBar'
import Head from 'next/head'
import Logo from '../components/Logo'
import Welcome from '../components/Welcome'

function Presentation()
{
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <HeadBar links={[
      {text:"Presentation", selected:true},
     {text:"Skills", selected:false},
      {text:"Games", selected:false},
      {text:"Projects", selected:false}]}>
      <Logo/>
    </HeadBar>
      <div className={styles.presentation}>
      <h1><span className={styles.hi}>Hi</span> , My Name is Carlos Arrieta</h1>
      <h3>{"I'm Computer Science Student"}</h3>

      </div>
      <div className={styles.description}>
        {/*<h1>{"<Welcome/>"}</h1>*/}
        <Welcome word = "Welcome" list = {["List", "Wisconsin", "Weigh", "Welcome", "Welter"]}/>
      </div>
      </div>
    )
}

export default Presentation;