import styles from '../styles/Presentation.module.css'
import HeadBar from '../components/HeadBar'
import Head from 'next/head'
import Logo from '../components/Logo'
import Welcome from '../components/Welcome'

function Presentation()
{

  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <HeadBar links={[
      {text:"Presentation", selected:false, link:"#"},
     {text:"Skills", selected:false, link:"#skillsPage" },
      {text:"Projects", selected:false, link:"#projectsPage"},
      {text:"Contact", selected:false, link:"#contactPage"}
      ]}>
      <Logo/>
    </HeadBar>
      <div className={styles.presentation}>

      <h1><span className={styles.hi}>Hi</span> , my name is Carlos Arrieta</h1>
      <h3>{"I'm Fullstack Developer"}</h3>

      </div>
      <div className={styles.description}>
        {/*<h1>{"<Welcome/>"}</h1>*/}
        <Welcome word = "Welcome" list = {["List", "Weigh", "Wisconsin",  "Welcome", "Welter"]}/>
      </div>
      </div>
    )
}

export default Presentation;